const table = {
    "a": "\u0b85",
    "aa": "\u0b86",
    "i": "\u0b87",
    "ii": "\u0b88",
    "u": "\u0b89",
    "uu": "\u0b8a",
    "e": "\u0b8e",
    "ee": "\u0b8f",
    "ai": "\u0b90",
    "o": "\u0b92",
    "oo": "\u0b93",
    "au": "\u0b94",

    "-a": "\u200b",
    "-aa": "\u0bbe",
    "-i": "\u0bbf",
    "-ii": "\u0bc0",
    "-u": "\u0bc1",
    "-uu": "\u0bc2",
    "-e": "\u0bc6",
    "-ee": "\u0bc7",
    "-ai": "\u0bc8",
    "-o": "\u0bca",
    "-oo": "\u0bcb",
    "-au": "\u0bcc",
    "-": "\u0bcd",

    "k": "\u0b95",
    "g": "\u0b95",
    "ng": "\u0b99",
    "s": "\u0b9a",
    "j": "\u0b9c",
    "ny": "\u0b9e",
    "d": "\u0b9f",
    "t": "\u0b9f",
    "N": "\u0ba3",
    "th": "\u0ba4",
    "n-": "\u0ba8",
    "n": "\u0ba9",
    "p": "\u0baa",
    "m": "\u0bae",
    "y": "\u0baf",
    "r": "\u0bb0",
    "R": "\u0bb1",
    "l": "\u0bb2",
    "L": "\u0bb3",
    "zh": "\u0bb4",
    "v": "\u0bb5",
    "sh": "\u0bb7",
    "S": "\u0bb8",
    "h": "\u0bb9",

    "consonants": [
        "k",
        "g",
        "ng",
        "s",
        "j",
        "ny",
        "d",
        "t",
        "N",
        "th",
        "n-",
        "n",
        "p",
        "m",
        "y",
        "r",
        "R",
        "l",
        "L",
        "zh",
        "v",
        "sh",
        "S",
        "h"
    ]
}